theme = "rose_pine"

[editor]
auto-save = true
auto-format=true
rulers = [80, 120]
cursorline = true
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
enable=true
display-messages = true

[editor.soft-wrap]
enable = true
max-wrap = 25

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.insert]
j = { k = "normal_mode" }
