theme = "everforest_dark"

[editor]
auto-save = true
auto-format=true
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
enable=true
auto-signature-help=true
display-messages = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.insert]
j = { k = "normal_mode" }
