#!/usr/bin/env bash

set -e
pushd ~/dotfiles/nix
hx machines/fern/configuration.nix
alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch --flake ~/dotfiles/nix/machines/fern/.#fern &>nixos-switch.log || (
 cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
popd
